version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/current
permissions:
  - object: /var/www/current
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/clear_current
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
